# 服务器配置
server:
  port: 8080

# 火山引擎大模型配置
volcengine:
  ark:
    region: cn-beijing
    api-key: 1a961b4b-8649-48ef-a035-a682b14c2049
    model-id: doubao-seed-1-6-vision-250815

# 图片处理参数配置
image:
  max-size: 5
  max-width: 6000
  max-height: 6000
